# Generated by Django 5.2.6 on 2025-09-19 06:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.TextField(blank=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Buddhism', 'Buddhism'), ('Christianity', 'Christianity'), ('Other', 'Other')], max_length=15)),
                ('nid', models.CharField(max_length=100)),
                ('passport', models.CharField(max_length=100)),
                ('driving_license', models.CharField(max_length=100)),
                ('corporate_id', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_system.company_info')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_system.user_role')),
            ],
        ),
    ]
