# Generated by Django 5.2.6 on 2025-09-21 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_system', '0002_alter_user_info_dob_alter_user_info_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendinguser',
            options={'ordering': ['-registered_at'], 'verbose_name': 'Pending User', 'verbose_name_plural': 'Pending Users'},
        ),
    ]
