# Generated by Django 5.2.6 on 2025-09-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_system', '0003_alter_pendinguser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='corporate_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='driving_license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='nid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='passport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='religion',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Buddhism', 'Buddhism'), ('Christianity', 'Christianity'), ('Other', 'Other')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
