# Generated by Django 5.2.6 on 2025-09-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_system', '0004_alter_pendinguser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
