# Generated by Django 5.2.6 on 2025-09-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_system', '0005_alter_user_info_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
