# Generated by Django 5.2.6 on 2025-09-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_system', '0006_alter_user_info_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='corporate_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='driving_license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='nid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='passport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='religion',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Buddhism', 'Buddhism'), ('Christianity', 'Christianity'), ('Other', 'Other')], max_length=15, null=True),
        ),
    ]
