# Generated by Django 5.2.6 on 2025-09-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_transactiondetail_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionGroupe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tran_groupe_name', models.CharField(max_length=255)),
                ('tran_groupe_type', models.BigIntegerField()),
                ('tran_method', models.CharField(max_length=255)),
                ('company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'transaction__groupes',
            },
        ),
    ]
