# Generated by Django 5.2.6 on 2025-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_transactiongroupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHead',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tran_head_name', models.CharField(max_length=255)),
                ('groupe_id', models.BigIntegerField()),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
                ('manufacturer_id', models.BigIntegerField(blank=True, null=True)),
                ('form_id', models.BigIntegerField(blank=True, null=True)),
                ('unit_id', models.BigIntegerField(default=1)),
                ('quantity', models.FloatField(default=0)),
                ('cp', models.FloatField(default=0)),
                ('mrp', models.FloatField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('editable', models.BooleanField(default=False)),
                ('company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'transaction__heads',
            },
        ),
    ]
