# Generated by Django 5.2.6 on 2025-09-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_transactionhead'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionMain',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tran_id', models.CharField(db_index=True, max_length=255)),
                ('tran_type', models.BigIntegerField()),
                ('tran_method', models.CharField(max_length=255)),
                ('invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('loc_id', models.BigIntegerField(blank=True, null=True)),
                ('tran_type_with', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('tran_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('tran_user', models.CharField(blank=True, max_length=255, null=True)),
                ('ptn_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('user_address', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_amount', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(default=0)),
                ('net_amount', models.FloatField(blank=True, null=True)),
                ('receive', models.FloatField(blank=True, null=True)),
                ('payment', models.FloatField(blank=True, null=True)),
                ('due', models.FloatField(blank=True, null=True)),
                ('due_col', models.FloatField(blank=True, default=0, null=True)),
                ('due_disc', models.FloatField(blank=True, default=0, null=True)),
                ('doc_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sr_id', models.CharField(blank=True, max_length=255, null=True)),
                ('store_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('payment_mode', models.BigIntegerField(blank=True, null=True)),
                ('booking_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tran_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'transaction__mains',
            },
        ),
    ]
