# Generated by Django 5.2.6 on 2025-09-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_transactionmain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionWith',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tran_with_name', models.CharField(max_length=255)),
                ('user_role', models.BigIntegerField()),
                ('tran_type', models.BigIntegerField()),
                ('tran_method', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'transaction__withs',
            },
        ),
    ]
