# Generated by Django 5.2.6 on 2025-09-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyPaymentRecieve',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tran_id', models.CharField(max_length=255)),
                ('tran_type', models.BigIntegerField()),
                ('tran_method', models.CharField(max_length=255)),
                ('invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('loc_id', models.BigIntegerField(blank=True, null=True)),
                ('tran_type_with', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('tran_user', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('user_address', models.CharField(blank=True, max_length=255, null=True)),
                ('tran_groupe_id', models.BigIntegerField(blank=True, null=True)),
                ('tran_head_id', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.FloatField(default=1)),
                ('bill_amount', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('net_amount', models.FloatField()),
                ('receive', models.FloatField(blank=True, null=True)),
                ('payment', models.FloatField(blank=True, null=True)),
                ('due', models.FloatField(default=0)),
                ('party_amount', models.FloatField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tran_date', models.DateTimeField(auto_now_add=True)),
                ('store_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('payment_mode', models.BigIntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'party_payment_recieves',
            },
        ),
    ]
