# Generated by Django 5.2.6 on 2025-09-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_id', models.BigIntegerField(blank=True, null=True)),
                ('category_name', models.CharField(max_length=255)),
                ('company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'item_categories',
            },
        ),
    ]
