# Generated by Django 5.2.6 on 2025-09-20 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_itemform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemform',
            name='type_id',
        ),
        migrations.AddField(
            model_name='itemform',
            name='type',
            field=models.ForeignKey(blank=True, db_column='type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemcategory'),
        ),
        migrations.AlterField(
            model_name='itemform',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name='itemform',
            table='item_forms',
        ),
    ]
