# Generated by Django 5.2.6 on 2025-09-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_itemform_type_id_itemform_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemForm',
        ),
    ]
