# Generated by Django 5.2.6 on 2025-09-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_itemmanufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=255)),
                ('company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.ForeignKey(blank=True, db_column='type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemcategory')),
            ],
            options={
                'db_table': 'item_units',
            },
        ),
    ]
